# Generated by Django 4.1.3 on 2022-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_article_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=23, upload_to='Category/photo'),
            preserve_default=False,
        ),
    ]
