# Generated by Django 4.1.3 on 2022-12-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='datetime_crated',
            new_name='datetime_created',
        ),
    ]
